#!/usr/bin/env bash
# demo/build.sh — executed by Cloudflare Pages at deploy time.
#
# Two jobs:
#   1. Generate demo/config.js from the MOBYDB_DEMO_KEY env var.
#      (config.js is .gitignored; the key lives in Cloudflare Pages
#       env vars only, never in the repo.)
#   2. Materialise demo/fixtures/ by copying ../fixtures/ into it.
#      Locally it's a symlink; Cloudflare's build environment does not
#      follow symlinks reliably, so we copy for deploy.
#
# Invocation (configured in Cloudflare Pages dashboard):
#   Build command:           cd demo && bash build.sh
#   Build output directory:  demo
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEMO_DIR="$REPO_ROOT/demo"

echo "[build.sh] repo root: $REPO_ROOT"
echo "[build.sh] demo dir:  $DEMO_DIR"

# --- 1. Generate config.js ---
if [[ -z "${MOBYDB_DEMO_KEY:-}" ]]; then
  echo "[build.sh] ERROR: MOBYDB_DEMO_KEY env var is not set in Cloudflare Pages."
  echo "[build.sh]        Add it under Pages project -> Settings -> Environment variables."
  exit 1
fi

cat > "$DEMO_DIR/config.js" <<CONFIG
// Generated by demo/build.sh at Cloudflare Pages build time.
// Do not edit by hand. The MOBYDB_DEMO_KEY env var lives in
// Cloudflare Pages and is injected here at build.
window.MOBYDB_DEMO_KEY = "${MOBYDB_DEMO_KEY}";
CONFIG

echo "[build.sh] wrote demo/config.js (key length: ${#MOBYDB_DEMO_KEY} chars)"

# --- 2. Materialise fixtures ---
rm -rf "$DEMO_DIR/fixtures"
if [[ -d "$REPO_ROOT/fixtures" ]]; then
  cp -R "$REPO_ROOT/fixtures" "$DEMO_DIR/fixtures"
  echo "[build.sh] copied $REPO_ROOT/fixtures -> $DEMO_DIR/fixtures"
  ls "$DEMO_DIR/fixtures/osm" | head -5
else
  echo "[build.sh] ERROR: $REPO_ROOT/fixtures not found. Aborting."
  exit 1
fi

echo "[build.sh] done."
